export const clientData = [
  {
    firstName: "Sumit",
    lastName: "Ranjan",
    company: "Twitter Inc",
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Mayur Vihar',
    payMethod: "Google Pay",
    type: "GST",
    status:'Active'
  },
  {
    company: "Square Inc",
    firstName: "Narendra",
    lastName: "Modi",
    mobileNumber: "+919413876754",
    flatNumber: "910",
    sector: "1",
    block: "B",
    locality:'Gurugram',
    payMethod: "Google Pay",
    type: "GST",
    status:'Active'
  },
  {
    company: "Shopify Inc",
    firstName: "Anil Ambani",
    lastName: "Ranjan",
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Saraswati Garden',
    payMethod: "Google Pay",
    type: "GST",
    status:'Active'
  },
  {
    company: "Sunrun Inc",
    firstName: "Bala",
    lastName: "Rajak",
    mobileNumber: "+919649240234",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Ashok Vihar',
    payMethod: "Google Pay",
    type: "Non-GST",
    status:'Active'
  },
  {
    company: "Adobe Inc",
    firstName: "Sumit",
    lastName: "Desai",
    mobileNumber: "+918521384918",
    flatNumber: "36/37",
    sector: "1",
    block: "A",
    locality:'Anand Vihar',
    payMethod: "Pay U",
    type: "GST",
    status:'Active'
  },
  {
    company: "HubSpot Inc",
    firstName: "Amit",
    lastName: "Ranjan",
    mobileNumber: "+919649440944",
    flatNumber: "56B",
    sector: "B",
    block: "2",
    locality:'PitamPura',
    payMethod: "Phone Pe",
    type: "Non-GST",
    status:'Active'
  },
    {
      firstName: "Sumit",
      lastName: "Ranjan",
      company: "Twitter Inc",
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Mayur Vihar',
      payMethod: "Google Pay",
      type: "GST",
      status:'Active'
    },
    {
      company: "Square Inc",
      firstName: "Narendra",
      lastName: "Modi",
      mobileNumber: "+919413876754",
      flatNumber: "910",
      sector: "1",
      block: "B",
      locality:'Gurugram',
      payMethod: "Google Pay",
      type: "GST",
      status:'Active'
    },
    {
      company: "Shopify Inc",
      firstName: "Anil Ambani",
      lastName: "Ranjan",
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Saraswati Garden',
      payMethod: "Google Pay",
      type: "GST",
      status:'Inactive'
    },
    {
      company: "Sunrun Inc",
      firstName: "Bala",
      lastName: "Rajak",
      mobileNumber: "+919649240234",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Ashok Vihar',
      payMethod: "Google Pay",
      type: "Non-GST",
      status:'Active'
    },
    {
      company: "Adobe Inc",
      firstName: "Sumit",
      lastName: "Desai",
      mobileNumber: "+918521384918",
      flatNumber: "36/37",
      sector: "1",
      block: "A",
      locality:'Anand Vihar',
      payMethod: "Pay U",
      type: "GST",
      status:'Active'
    },
    {
      company: "HubSpot Inc",
      firstName: "Amit",
      lastName: "Ranjan",
      mobileNumber: "+919649440944",
      flatNumber: "56B",
      sector: "B",
      block: "2",
      locality:'PitamPura',
      payMethod: "Phone Pe",
      type: "Non-GST",
      status:'Inactive'
    },  

];

export const factoryData = [
  {
    company: "Twitter Inc",
    mobileNumber: "+919649240944",
    owner:clientData[0].firstName+clientData[0].lastName,
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Mayur Vihar',
    payMethod: "Google Pay",
    type: "GST",
    status:"Active"
  },
  {
    company: "Square Inc",
    owner:clientData[1].firstName+clientData[1].lastName,
    
    mobileNumber: "+919413876754",
    flatNumber: "910",
    sector: "1",
    block: "B",
    locality:'Gurugram',
    payMethod: "Google Pay",
    type: "GST",
    status:'Inactive'
  },
  {
    company: "Shopify Inc",
    owner:clientData[2].firstName+clientData[2].lastName,
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Saraswati Garden',
    payMethod: "Google Pay",
    type: "GST",
    status:"Active"
  },
  {
    company: "Sunrun Inc",
    owner:clientData[3].firstName+clientData[3].lastName,
    mobileNumber: "+919649240234",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Ashok Vihar',
    payMethod: "Google Pay",
    type: "Non-GST",
    status:"Active"
  },
  {
    company: "Adobe Inc",
    owner:clientData[4].firstName+clientData[4].lastName,
    mobileNumber: "+918521384918",
    flatNumber: "36/37",
    sector: "1",
    block: "A",
    locality:'Anand Vihar',
    payMethod: "Pay U",
    type: "GST",
    status:"Inactive"
  },
  {
    company: "HubSpot Inc",
    owner:clientData[5].firstName+clientData[5].lastName,
    mobileNumber: "+919649440944",
    flatNumber: "56B",
    sector: "B",
    block: "2",
    locality:'PitamPura',
    payMethod: "Phone Pe",
    type: "Non-GST",
    status:"Active"
  },
    {
      owner:clientData[6].firstName+clientData[6].lastName,
      company: "Facebook Inc",
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Mayur Vihar',
      payMethod: "Google Pay",
      type: "GST",
      status:"Active"
    },
    {
      company: "FourSquare Inc",
      owner:clientData[7].firstName+clientData[7].lastName,
      mobileNumber: "+919413876754",
      flatNumber: "910",
      sector: "1",
      block: "B",
      locality:'Gurugram',
      payMethod: "Google Pay",
      type: "GST",
      status:"Active"
    },
    {
      company: "Paytm Inc",
      owner:clientData[8].firstName+clientData[8].lastName,
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Saraswati Garden',
      payMethod: "Google Pay",
      type: "GST",
      status:"Active"

    },
    {
      company: "DLC City Inc",
      owner:clientData[9].firstName+clientData[9].lastName,
      mobileNumber: "+919649240234",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Ashok Vihar',
      payMethod: "Google Pay",
      type: "Non-GST",
      status:"Inactive"
    },
    {
      company: "DMRC Inc",
      owner:clientData[10].firstName+clientData[10].lastName,
      mobileNumber: "+918521384918",
      flatNumber: "36/37",
      sector: "1",
      block: "A",
      locality:'Anand Vihar',
      payMethod: "Pay U",
      type: "GST",
      status:"Active"
    },
    {
      company: "International Mastercard Inc",
      owner:clientData[11].firstName+' '+clientData[11].lastName,
      mobileNumber: "+919649440944",
      flatNumber: "56B",
      sector: "B",
      block: "2",
      locality:'PitamPura',
      payMethod: "Phone Pe",
      type: "Non-GST",
      status:"Inactive"
    },  

];

export const groupData = [
  
  {
    groupName:'A',
    company: "HubSpot Inc",
    firstName: "Amit",
    lastName: "Ranjan",
    mobileNumber: "+919649440944",
    flatNumber: "56B",
    sector: "B",
    block: "2",
    locality:'PitamPura',
    payMethod: "Phone Pe",
    type: "Non-GST",
    status:'Active'
  },
    {
      groupName:'B',
      firstName: "Sumit",
      lastName: "Ranjan",
      company: "Twitter Inc",
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Mayur Vihar',
      payMethod: "Google Pay",
      type: "GST",
      status:'Active'
    },
    {
      groupName:'C',
      company: "Square Inc",
      firstName: "Narendra",
      lastName: "Modi",
      mobileNumber: "+919413876754",
      flatNumber: "910",
      sector: "1",
      block: "B",
      locality:'Gurugram',
      payMethod: "Google Pay",
      type: "GST",
      status:'Active'
    },
    

];

export const subscriptionData = [
  {
    firstName: "Sumit",
    lastName: "Ranjan",
    company: "Twitter Inc",
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Mayur Vihar',
    payMethod: "Google Pay",
    type: "GST",
    status:'Active',
    start:'12-Dec-2020',
    end:'28-Feb-2021'
  },
  {
    company: "Square Inc",
    firstName: "Narendra",
    lastName: "Modi",
    mobileNumber: "+919413876754",
    flatNumber: "910",
    sector: "1",
    block: "B",
    locality:'Gurugram',
    payMethod: "Google Pay",
    type: "GST",
    status:'Active',
    start:'12-Dec-2020',
    end:'28-Feb-2021'
  },
  {
    company: "Shopify Inc",
    firstName: "Anil Ambani",
    lastName: "Ranjan",
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Saraswati Garden',
    payMethod: "Google Pay",
    type: "GST",
    status:'Active',
    start:'12-Dec-2020',
    end:'28-Feb-2021'
  },
  {
    company: "Sunrun Inc",
    firstName: "Bala",
    lastName: "Rajak",
    mobileNumber: "+919649240234",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Ashok Vihar',
    payMethod: "Google Pay",
    type: "Non-GST",
    status:'Active',
    start:'12-Dec-2020',
    end:'28-Feb-2021'
  },
  {
    company: "Adobe Inc",
    firstName: "Sumit",
    lastName: "Desai",
    mobileNumber: "+918521384918",
    flatNumber: "36/37",
    sector: "1",
    block: "A",
    locality:'Anand Vihar',
    payMethod: "Pay U",
    type: "GST",
    end:'28-Feb-2021',
    start:'12-Dec-2020',
    status:'Active',
  },
  {
    company: "HubSpot Inc",
    firstName: "Amit",
    lastName: "Ranjan",
    mobileNumber: "+919649440944",
    flatNumber: "56B",
    sector: "B",
    block: "2",
    locality:'PitamPura',
    payMethod: "Phone Pe",
    type: "Non-GST",
    status:'Active',
    end:'28-Feb-2021',
    start:'12-Dec-2020',
  },
    {
      firstName: "Sumit",
      lastName: "Ranjan",
      company: "Twitter Inc",
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Mayur Vihar',
      payMethod: "Google Pay",
      type: "GST",
      status:'Active',
      end:'28-Feb-2021',
      start:'12-Dec-2020',
    },
    {
      company: "Square Inc",
      firstName: "Narendra",
      lastName: "Modi",
      mobileNumber: "+919413876754",
      flatNumber: "910",
      sector: "1",
      block: "B",
      locality:'Gurugram',
      payMethod: "Google Pay",
      type: "GST",
      status:'Active',
      end:'28-Feb-2021',
      start:'12-Dec-2020',
    },
    {
      company: "Shopify Inc",
      firstName: "Anil Ambani",
      lastName: "Ranjan",
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Saraswati Garden',
      payMethod: "Google Pay",
      type: "GST",
      status:'Inactive',
      end:'28-Feb-2021',
      start:'12-Dec-2020',
    },
    {
      company: "Sunrun Inc",
      firstName: "Bala",
      lastName: "Rajak",
      mobileNumber: "+919649240234",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Ashok Vihar',
      payMethod: "Google Pay",
      type: "Non-GST",
      status:'Inactive',
      end:'28-Feb-2021',
      start:'12-Dec-2020',
    },
    {
      company: "Adobe Inc",
      firstName: "Sumit",
      lastName: "Desai",
      mobileNumber: "+918521384918",
      flatNumber: "36/37",
      sector: "1",
      block: "A",
      locality:'Anand Vihar',
      payMethod: "Pay U",
      type: "GST",
      status:'Active',
      end:'28-Feb-2021',
      start:'12-Dec-2020',
    },
    {
      company: "HubSpot Inc",
      firstName: "Amit",
      lastName: "Ranjan",
      mobileNumber: "+919649440944",
      flatNumber: "56B",
      sector: "B",
      block: "2",
      locality:'PitamPura',
      payMethod: "Phone Pe",
      type: "Non-GST",
      status:'Active',
      end:'28-Feb-2021',
      start:'12-Dec-2020',
    },  

];

export const paymentData = [
  {
    firstName: "Sumit",
    lastName: "Ranjan",
    company: "Twitter Inc",
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Mayur Vihar',
    payMethod: "Google Pay",
    type: "GST",
    advance:'Nil',
    duedate:'28-12-2020',
    status:'Paid',
    discount:'10%'
  },
  {
    company: "Square Inc",
    firstName: "Narendra",
    lastName: "Modi",
    mobileNumber: "+919413876754",
    flatNumber: "910",
    sector: "1",
    block: "B",
    locality:'Gurugram',
    payMethod: "Google Pay",
    type: "GST",
    advance:'20000',
    duedate:'30-12-2020',
    status:'Paid',
    discount:'20%'
  },
  {
    company: "Shopify Inc",
    firstName: "Anil Ambani",
    lastName: "Ranjan",
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Saraswati Garden',
    payMethod: "Google Pay",
    type: "GST",
    advance:'Nil',
    duedate:'01-01-2021',
    status:'Pending',
    discount:'0'
  },
  {
    company: "Sunrun Inc",
    firstName: "Bala",
    lastName: "Rajak",
    mobileNumber: "+919649240234",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Ashok Vihar',
    payMethod: "Google Pay",
    type: "Non-GST",
    advance:'5000',
    duedate:'28-12-2020',
    status:'Paid',
    discount:'5%'
  },
  {
    company: "Adobe Inc",
    firstName: "Sumit",
    lastName: "Desai",
    mobileNumber: "+918521384918",
    flatNumber: "36/37",
    sector: "1",
    block: "A",
    locality:'Anand Vihar',
    payMethod: "Pay U",
    type: "GST",
    advance:'Nil',
    duedate:'28-12-2020',
    status:'pending',
    discount:'7%'
  },
  {
    company: "HubSpot Inc",
    firstName: "Amit",
    lastName: "Ranjan",
    mobileNumber: "+919649440944",
    flatNumber: "56B",
    sector: "B",
    block: "2",
    locality:'PitamPura',
    payMethod: "Phone Pe",
    type: "Non-GST",
    advance:'1000',
    duedate:'28-02-2020',
    status:'Paid',
    discount:'2%'
  },
    {
      firstName: "Sumit",
      lastName: "Ranjan",
      company: "Twitter Inc",
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Mayur Vihar',
      payMethod: "Google Pay",
      type: "GST",
      advance:'10000',
      duedate:'28-12-2020',
      status:'Paid',
      discount:'10%'
    },
    {
      company: "Square Inc",
      firstName: "Narendra",
      lastName: "Modi",
      mobileNumber: "+919413876754",
      flatNumber: "910",
      sector: "1",
      block: "B",
      locality:'Gurugram',
      payMethod: "Google Pay",
      type: "GST",
      advance:'Nil',
      duedate:'25-12-2020',
      status:'pending',
      discount:'10%'
    },
    {
      company: "Shopify Inc",
      firstName: "Anil Ambani",
      lastName: "Ranjan",
      mobileNumber: "+919649240944",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Saraswati Garden',
      payMethod: "Google Pay",
      type: "GST",
      advance:'24000',
      duedate:'29-12-2020',
      status:'pending',
      discount:'5%'
    },
    {
      company: "Sunrun Inc",
      firstName: "Bala",
      lastName: "Rajak",
      mobileNumber: "+919649240234",
      flatNumber: "36/37",
      sector: "1",
      block: "B",
      locality:'Ashok Vihar',
      payMethod: "Google Pay",
      type: "Non-GST",    
      advance:'Nil',
      duedate:'28-12-2020',
      status:'Paid',
      discount:'10%'
    },
    {
      company: "Adobe Inc",
      firstName: "Sumit",
      lastName: "Desai",
      mobileNumber: "+918521384918",
      flatNumber: "36/37",
      sector: "1",
      block: "A",
      locality:'Anand Vihar',
      payMethod: "Pay U",
      type: "GST",
      advance:'2800',
      duedate:'28-12-2020',
      status:'Paid',
      discount:'10%'
    },
    {
      company: "HubSpot Inc",
      firstName: "Amit",
      lastName: "Ranjan",
      mobileNumber: "+919649440944",
      flatNumber: "56B",
      sector: "B",
      block: "2",
      locality:'PitamPura',
      payMethod: "Phone Pe",
      type: "Non-GST",
      advance:'40000',
      duedate:'28-12-2020',
      status:'Paid',
      discount:'10%'
    },  

];
