export const stockData = [
  {
    firstName: "Sumit",
    lastName: "Ranjan",
    company: "Twitter Inc",
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Mayur Vihar',
    payMethod: "Google Pay",
    type: "GST",
  },
  {
    company: "Square Inc",
    firstName: "Narendra",
    lastName: "Modi",
    mobileNumber: "+919413876754",
    flatNumber: "910",
    sector: "1",
    block: "B",
    locality:'Gurugram',
    payMethod: "Google Pay",
    type: "GST",
  },
  {
    company: "Shopify Inc",
    firstName: "Anil Ambani",
    lastName: "Ranjan",
    mobileNumber: "+919649240944",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Saraswati Garden',
    payMethod: "Google Pay",
    type: "GST",
  },
  {
    company: "Sunrun Inc",
    firstName: "Bala",
    lastName: "Rajak",
    mobileNumber: "+919649240234",
    flatNumber: "36/37",
    sector: "1",
    block: "B",
    locality:'Ashok Vihar',
    payMethod: "Google Pay",
    type: "Non-GST",
  },
  {
    company: "Adobe Inc",
    firstName: "Sumit",
    lastName: "Desai",
    mobileNumber: "+918521384918",
    flatNumber: "36/37",
    sector: "1",
    block: "A",
    locality:'Anand Vihar',
    payMethod: "Pay U",
    type: "GST",
  },
  {
    company: "HubSpot Inc",
    firstName: "Amit",
    lastName: "Ranjan",
    mobileNumber: "+919649440944",
    flatNumber: "56B",
    sector: "B",
    block: "2",
    locality:'PitamPura',
    payMethod: "Phone Pe",
    type: "Non-GST",
  },
];
